name: "imagedream-nerf-refine"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "mvdream-random-multiview-camera-datamodule"
data:
  batch_size: [4, 4] # must be dividable by n_view
  n_view: 4
  # 0-3499: 256x256, >=2500: 1024x1024
  width: [256, 1024] 
  height: [256, 1024] 
  eval_width: 1024
  eval_height: 1024
  resolution_milestones: [2500]
  camera_distance_range: [0.6, 0.75] # [0.8, 1.0] 
  fovy_range: [45, 50] # [15, 60] 
  elevation_range: [0, 5] # [0, 30]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  n_val_views: 4
  eval_camera_distance: 2.0 # 3.0 
  eval_fovy_deg: 40. 

system_type: "mvdream-system"
system:
  image: true
  refinement: true
  geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 # consistent with coarse

    isosurface_resolution: 128
    isosurface_deformable_grid: true
    pos_encoding_config: # consistent with coarse, no progressive band
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.4472692374403782 # max resolution 4096
    fix_geometry: false # optimize grid sdf and deformation

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 0
    soft_shading: true

  background_type: "neural-environment-map-background"

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: cuda

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    image_path: ???
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "image-multiview-diffusion-guidance"
  guidance:
    model_name: "sd-v2.1-base-4view-ipmv"
    ckpt_path: null # path to a pre-downloaded checkpoint file (null for loading from URL)
    guidance_scale: 5.0
    min_step_percent: [0, 0.98, 0.02, 8000]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [0, 0.98, 0.50, 8000]
    ip_mode: "pixel"


  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 1.
    lambda_normal_consistency: 10000.

  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    #params:
    #  geometry:
      #geometry.encoding:
      #  lr: 0.01
      #geometry.density_network:
      #  lr: 0.001
      #geometry.feature_network:
      #  lr: 0.001
      #background:
      #  lr: 0.001

trainer:
  max_steps: 5000 
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 100
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
